print ("Hello world")

message = "Hello world"
print (message)

name = "ada lovelace"
print(name.title())
print(name.upper())
print(name.lower())

first_name = "ada"
last_name = "lace"
full_name = first_name + " " + last_name + "!"
print(full_name)

print ("python")
print ("\tpython")

print ("languages: \n\tpython \n\tC \n\tjava \n\tjavascript")

message  = "One of python's strengths is it's diverse community."
print (message)


